"""Shared domain and engine contracts for the local-first SPLICR Studio."""

from .domain import (
    Artifact,
    ArtifactKind,
    Project,
    RenderPlan,
    RenderSegment,
    Take,
    TakeStatus,
    VoiceProfile,
    VoiceProfileKind,
)
from .engines import (
    EngineAdapter,
    EngineDescriptor,
    EngineSession,
    EngineSessionContext,
    EngineTransport,
    ProviderEngineAdapter,
    engine_adapter_for_provider,
)
from .local_subprocess import LocalSubprocessEngineAdapter, LocalSubprocessSpec
from .migration import (
    ImportedJob,
    ImportedNarratorCustomizations,
    ImportedNarratorProject,
    ImportedNarratorVoice,
    NarratorProjectManifest,
    NarratorSnapshot,
    NarratorVoiceManifest,
    import_narrator_customizations,
    import_narrator_projects,
    import_narrator_voices,
    import_splicr_job,
    import_splicr_jobs,
    scan_narrator_data,
)
from .store import ImportRecord, SqliteStudioStore
from .subtitles import (
    SubtitleCue,
    SubtitleExport,
    SubtitleFormat,
    SubtitleService,
    SubtitleTimeline,
    SubtitleTimingConfidence,
    SubtitleTimingSource,
    serialize_subtitles,
)
from .transcription import (
    TranscriptionJob,
    TranscriptionJobService,
    TranscriptionJobStatus,
    TranscriptionOptions,
    TranscriptionProvider,
    TranscriptionProviderDescriptor,
    TranscriptionResult,
    TranscriptionSegment,
    TranscriptionWord,
)

__all__ = [
    "Artifact",
    "ArtifactKind",
    "EngineAdapter",
    "EngineDescriptor",
    "EngineSession",
    "EngineSessionContext",
    "EngineTransport",
    "LocalSubprocessEngineAdapter",
    "LocalSubprocessSpec",
    "ImportRecord",
    "ImportedJob",
    "ImportedNarratorCustomizations",
    "ImportedNarratorProject",
    "ImportedNarratorVoice",
    "NarratorProjectManifest",
    "NarratorSnapshot",
    "NarratorVoiceManifest",
    "Project",
    "ProviderEngineAdapter",
    "RenderPlan",
    "RenderSegment",
    "Take",
    "TakeStatus",
    "VoiceProfile",
    "VoiceProfileKind",
    "SqliteStudioStore",
    "SubtitleCue",
    "SubtitleExport",
    "SubtitleFormat",
    "SubtitleService",
    "SubtitleTimeline",
    "SubtitleTimingConfidence",
    "SubtitleTimingSource",
    "TranscriptionJob",
    "TranscriptionJobService",
    "TranscriptionJobStatus",
    "TranscriptionOptions",
    "TranscriptionProvider",
    "TranscriptionProviderDescriptor",
    "TranscriptionResult",
    "TranscriptionSegment",
    "TranscriptionWord",
    "engine_adapter_for_provider",
    "import_narrator_customizations",
    "import_narrator_projects",
    "import_narrator_voices",
    "import_splicr_job",
    "import_splicr_jobs",
    "scan_narrator_data",
    "serialize_subtitles",
]
